# Assignment 1 NumPy



In [1]:
#Import the libraries 
import numpy as np

# Problem 1 
Matrix Manipulations

Lets first create a matrix and perform some manipulations of it.

Using numpy's matrix data structure, define the following matricies:

$$A=\left[ \begin{array}{ccc} 3 & 5 & 9 \\ 3 & 3 & 4 \\ 5 & 9 & 17 \end{array} \right]$$

$$B=\left[ \begin{array}{c} 2 \\ 1 \\ 4 \end{array} \right]$$

After this solve the matrix equation:
$$Ax = B$$

In [2]:
a=np.array([[3,5,9],[3,3,4],[5,9,17]])
a

array([[ 3,  5,  9],
       [ 3,  3,  4],
       [ 5,  9, 17]])

In [3]:
b=np.array([[2],[1],[4]])
b

array([[2],
       [1],
       [4]])

In [5]:
# Solving the matrix Ax=B
# The values of x will be as follows:
print ("Solutions:\n",np.linalg.solve(a, b ) )

Solutions:
 [[ 1.]
 [-2.]
 [ 1.]]


# Problem 2
Create a result array by adding the following two NumPy arrays. Next, modify the result array by calculating the square of each element
Input: $$arrayOne = \left[\begin{array}{ccc} 5& 6& 9\\ 21 & 18 & 27\end{array}\right]$$
       $$arrayTwo = \left[\begin{array}{ccc} 15 &33& 24\\ 4 &7& 1\end{array}\right]$$



In [6]:
a=np.array([[5,6,9],[21,18,27]])
a

array([[ 5,  6,  9],
       [21, 18, 27]])

In [7]:
b=np.array([[15,33,24],[4,7,1]])
b

array([[15, 33, 24],
       [ 4,  7,  1]])

In [10]:
# Adding two arrays
c=a+b
c

array([[20, 39, 33],
       [25, 25, 28]])

In [12]:
# Finding out squares of elements
d=c*c
d

array([[ 400, 1521, 1089],
       [ 625,  625,  784]])

# Problem 3
Print max from axis 0 and min from axis 1 from the following 2-D array.\
$$sampleArray = \left[\begin{array}{ccc} 34&43&73 \\ 82&22&12 \\ 53&94&66 \end{array}\right]$$




In [13]:
arr=np.array([[34,43,73],[82,22,12],[53,94,66]])
arr


array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [14]:
# Finding Max value from axis=0
arr.max(axis=0)

array([82, 94, 73])

In [15]:
# Finding Min value from axis=1
arr.min(axis=1)

array([34, 12, 53])

# Problem 4
Get the positions where elements of a and b match\
Input:  a = np.array([1,2,3,2,3,4,3,4,5,6])\
b = np.array([7,2,10,2,7,4,9,4,9,8])\
Desired Output: array([1, 3, 5, 7])

In [17]:
arr1=np.array([1,2,3,2,3,4,3,4,5,6])
arr1

array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])

In [18]:
arr2=np.array([7,2,10,2,7,4,9,4,9,8])
arr2

array([ 7,  2, 10,  2,  7,  4,  9,  4,  9,  8])

In [21]:
# Positions where A and B matches is as follows:
np.arange(len(arr1))[arr1==arr2]

array([1, 3, 5, 7])

# Problem 5
Given 
$$a= \left[\begin{array}{cc} 1&2\\ 3&4 \end{array}\right]$$
$$b = \left[\begin{array}{cc} 5&6 \\ 7&8 \end{array}\right]$$
Obtain c and d
$$c = \left[\begin{array}{cc} 1&2\\ 3&4 \\ 5&6 \\ 7&8 \end{array}\right]$$
$$d = \left[\begin{array}{cccc} 1&2&5&6\\ 3&4&7&8 \end{array}\right]$$

In [22]:
a=np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [23]:
b=np.array([[5,6],[7,8]])
b

array([[5, 6],
       [7, 8]])

In [25]:
# concatenating row wise
c=np.concatenate((a,b),axis=0)
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [26]:
# Concatenating column wise
d=np.concatenate((a,b),axis=1)
d

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])