# Assignment 01
## Given credit_card_default dataset
### • Do the pre-processing on dataset
### • Perform different algorithms such as kNN,SVM, Gradient Boosting, Ada boosting and XG Boost
### • Also perform hyperparameter tuning

In [188]:
#import necessary models
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [189]:
from google.colab import files
uploaded=files.upload()

Saving credit_card_default.csv to credit_card_default (2).csv


In [190]:
#reading data from CSV file
data = pd.read_csv("credit_card_default.csv")

In [191]:
data

ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_1  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       PAY_4  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  \
0         -1  ...          0          0          0         0       689   
1          0  ...       3272       3455       3261         0      1000   
2          0  ...      14331      14948      15549      1518      1500   
3          0  ...      28314      28959      29547      2000      2019   
4          0  ...      20940      19146      19131      2000     36681   
...      ...  ...        ...        ...        ...       ...       ...   
29995      0  ...      88004      31237      15980      8500     20000   
29996     -1  ...       8979       5190          0      1837      3526   
29997     -1  ...      20878      20582      19357         0         0   
29998      0  ...      52774      11855      48944     85900      3409   
29999      0  ...      36535      32428      15313      2078      1800   

       PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  default payment next month  
0             0         0         0         0                           1  
1          1000      1000         0      2000                           1  
2          1000      1000      1000      5000                           0  
3          1200      1100      1069      1000                           0  
4         10000      9000       689       679                           0  
...         ...       ...       ...       ...                         ...  
29995      5003      3047      5000      1000                           0  
29996      8998       129         0         0                           0  
29997     22000      4200      2000      3100                           1  
29998      1178      1926     52964      1804                           1  
29999      1430      1000      1000      1000                           1  

[30000 rows x 25 columns]

In [192]:
data.columns

Index(['ID', 'LIMIT_BAL', 'SEX', 'EDUCATION', 'MARRIAGE', 'AGE', 'PAY_1',
       'PAY_2', 'PAY_3', 'PAY_4', 'PAY_5', 'PAY_6', 'BILL_AMT1', 'BILL_AMT2',
       'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6', 'PAY_AMT1',
       'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6',
       'default payment next month'],
      dtype='object')

In [193]:
#Renaming columns to lower letters for coding convenience
data = data.rename(columns = lambda x: x.lower())

In [194]:
#Renaming the column names to some simple name
data = data.rename(columns = {"default payment next month":"default"})

In [195]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 25 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         30000 non-null  int64
 1   limit_bal  30000 non-null  int64
 2   sex        30000 non-null  int64
 3   education  30000 non-null  int64
 4   marriage   30000 non-null  int64
 5   age        30000 non-null  int64
 6   pay_1      30000 non-null  int64
 7   pay_2      30000 non-null  int64
 8   pay_3      30000 non-null  int64
 9   pay_4      30000 non-null  int64
 10  pay_5      30000 non-null  int64
 11  pay_6      30000 non-null  int64
 12  bill_amt1  30000 non-null  int64
 13  bill_amt2  30000 non-null  int64
 14  bill_amt3  30000 non-null  int64
 15  bill_amt4  30000 non-null  int64
 16  bill_amt5  30000 non-null  int64
 17  bill_amt6  30000 non-null  int64
 18  pay_amt1   30000 non-null  int64
 19  pay_amt2   30000 non-null  int64
 20  pay_amt3   30000 non-null  int64
 21  pay_amt4   3

It is seen that all the field values are numerical values

In [196]:
#sex, education and marriage should ideally be categorical variable. Lets find it out
#distinct values with count
data['sex'].value_counts()

2    18112
1    11888
Name: sex, dtype: int64

In [197]:
data['education'].value_counts()

2    14030
1    10585
3     4917
5      280
4      123
6       51
0       14
Name: education, dtype: int64

In [198]:
data['marriage'].value_counts()

2    15964
1    13713
3      323
Name: marriage, dtype: int64

In [199]:
#add new feature Male to the dataset   
# 0 --> false, 1 -->True
data["male"] = (data['sex'] == 1).astype(int)

In [200]:
data

id  limit_bal  sex  education  marriage  age  pay_1  pay_2  pay_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       pay_4  ...  bill_amt5  bill_amt6  pay_amt1  pay_amt2  pay_amt3  \
0         -1  ...          0          0         0       689         0   
1          0  ...       3455       3261         0      1000      1000   
2          0  ...      14948      15549      1518      1500      1000   
3          0  ...      28959      29547      2000      2019      1200   
4          0  ...      19146      19131      2000     36681     10000   
...      ...  ...        ...        ...       ...       ...       ...   
29995      0  ...      31237      15980      8500     20000      5003   
29996     -1  ...       5190          0      1837      3526      8998   
29997     -1  ...      20582      19357         0         0     22000   
29998      0  ...      11855      48944     85900      3409      1178   
29999      0  ...      32428      15313      2078      1800      1430   

       pay_amt4  pay_amt5  pay_amt6  default  male  
0             0         0         0        1     0  
1          1000         0      2000        1     0  
2          1000      1000      5000        0     0  
3          1100      1069      1000        0     0  
4          9000       689       679        0     1  
...         ...       ...       ...      ...   ...  
29995      3047      5000      1000        0     1  
29996       129         0         0        0     1  
29997      4200      2000      3100        1     1  
29998      1926     52964      1804        1     1  
29999      1000      1000      1000        1     1  

[30000 rows x 26 columns]

In [201]:
#Now, we will check for education column
# 1 assume that it is graduation , 0 is not
data['grad_school'] = (data['education']==1).astype(int)

In [202]:
data

id  limit_bal  sex  education  marriage  age  pay_1  pay_2  pay_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       pay_4  ...  bill_amt6  pay_amt1  pay_amt2  pay_amt3  pay_amt4  \
0         -1  ...          0         0       689         0         0   
1          0  ...       3261         0      1000      1000      1000   
2          0  ...      15549      1518      1500      1000      1000   
3          0  ...      29547      2000      2019      1200      1100   
4          0  ...      19131      2000     36681     10000      9000   
...      ...  ...        ...       ...       ...       ...       ...   
29995      0  ...      15980      8500     20000      5003      3047   
29996     -1  ...          0      1837      3526      8998       129   
29997     -1  ...      19357         0         0     22000      4200   
29998      0  ...      48944     85900      3409      1178      1926   
29999      0  ...      15313      2078      1800      1430      1000   

       pay_amt5  pay_amt6  default  male  grad_school  
0             0         0        1     0            0  
1             0      2000        1     0            0  
2          1000      5000        0     0            0  
3          1069      1000        0     0            0  
4           689       679        0     1            0  
...         ...       ...      ...   ...          ...  
29995      5000      1000        0     1            0  
29996         0         0        0     1            0  
29997      2000      3100        1     1            0  
29998     52964      1804        1     1            0  
29999      1000      1000        1     1            0  

[30000 rows x 27 columns]

In [203]:
#assume 2 as university
data["university"] = (data['education']==2).astype(int)

In [204]:
data

id  limit_bal  sex  education  marriage  age  pay_1  pay_2  pay_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       pay_4  ...  pay_amt1  pay_amt2  pay_amt3  pay_amt4  pay_amt5  pay_amt6  \
0         -1  ...         0       689         0         0         0         0   
1          0  ...         0      1000      1000      1000         0      2000   
2          0  ...      1518      1500      1000      1000      1000      5000   
3          0  ...      2000      2019      1200      1100      1069      1000   
4          0  ...      2000     36681     10000      9000       689       679   
...      ...  ...       ...       ...       ...       ...       ...       ...   
29995      0  ...      8500     20000      5003      3047      5000      1000   
29996     -1  ...      1837      3526      8998       129         0         0   
29997     -1  ...         0         0     22000      4200      2000      3100   
29998      0  ...     85900      3409      1178      1926     52964      1804   
29999      0  ...      2078      1800      1430      1000      1000      1000   

       default  male  grad_school  university  
0            1     0            0           1  
1            1     0            0           1  
2            0     0            0           1  
3            0     0            0           1  
4            0     1            0           1  
...        ...   ...          ...         ...  
29995        0     1            0           0  
29996        0     1            0           0  
29997        1     1            0           1  
29998        1     1            0           0  
29999        1     1            0           1  

[30000 rows x 28 columns]

In [205]:
#assume value 1 as married
data["married"] = (data['marriage']==1).astype(int)

In [206]:
data

id  limit_bal  sex  education  marriage  age  pay_1  pay_2  pay_3  \
0          1      20000    2          2         1   24      2      2     -1   
1          2     120000    2          2         2   26     -1      2      0   
2          3      90000    2          2         2   34      0      0      0   
3          4      50000    2          2         1   37      0      0      0   
4          5      50000    1          2         1   57     -1      0     -1   
...      ...        ...  ...        ...       ...  ...    ...    ...    ...   
29995  29996     220000    1          3         1   39      0      0      0   
29996  29997     150000    1          3         2   43     -1     -1     -1   
29997  29998      30000    1          2         2   37      4      3      2   
29998  29999      80000    1          3         1   41      1     -1      0   
29999  30000      50000    1          2         1   46      0      0      0   

       pay_4  ...  pay_amt2  pay_amt3  pay_amt4  pay_amt5  pay_amt6  default  \
0         -1  ...       689         0         0         0         0        1   
1          0  ...      1000      1000      1000         0      2000        1   
2          0  ...      1500      1000      1000      1000      5000        0   
3          0  ...      2019      1200      1100      1069      1000        0   
4          0  ...     36681     10000      9000       689       679        0   
...      ...  ...       ...       ...       ...       ...       ...      ...   
29995      0  ...     20000      5003      3047      5000      1000        0   
29996     -1  ...      3526      8998       129         0         0        0   
29997     -1  ...         0     22000      4200      2000      3100        1   
29998      0  ...      3409      1178      1926     52964      1804        1   
29999      0  ...      1800      1430      1000      1000      1000        1   

       male  grad_school  university  married  
0         0            0           1        1  
1         0            0           1        0  
2         0            0           1        0  
3         0            0           1        1  
4         1            0           1        1  
...     ...          ...         ...      ...  
29995     1            0           0        1  
29996     1            0           0        0  
29997     1            0           1        0  
29998     1            0           0        1  
29999     1            0           1        1  

[30000 rows x 29 columns]

In [207]:
data.columns

Index(['id', 'limit_bal', 'sex', 'education', 'marriage', 'age', 'pay_1',
       'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6', 'bill_amt1', 'bill_amt2',
       'bill_amt3', 'bill_amt4', 'bill_amt5', 'bill_amt6', 'pay_amt1',
       'pay_amt2', 'pay_amt3', 'pay_amt4', 'pay_amt5', 'pay_amt6', 'default',
       'male', 'grad_school', 'university', 'married'],
      dtype='object')

Thus, new fields are added

In [208]:
# Now, we will split the data to Bill Amount related features and Payment amount related features
bill_amt_features = ["bill_amt" + str(i) for i in range(1,7)]
pay_amt_features = ["pay_amt" + str(i) for i in range(1,7)]

In [209]:
#As new columns, we have modified the dataset with binary values using above-mentioned codes. Now we will split the data to binary features.
binary_features = ['male', 'grad_school', 'university', 'married']

In [210]:
pay_features = ["pay_" + str(i) for i in range(1,7)]

In [211]:
pay_features

['pay_1', 'pay_2', 'pay_3', 'pay_4', 'pay_5', 'pay_6']

In [212]:
 #Segregating Numerical features in the dataset
 num_features = ["limit_bal", "age"] + bill_amt_features + pay_amt_features + pay_features

In [213]:
#Now, we will define the Features (x) as numerical and binary values
x = data[num_features + binary_features]

In [214]:
#Defining Target variable
y = data['default']

In [215]:
#Splitting to Test and Train datasets
from sklearn.model_selection import train_test_split

In [216]:
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                                    test_size=0.2, 
                                                    random_state = 134)

In [217]:
x_train

limit_bal  age  bill_amt1  bill_amt2  bill_amt3  bill_amt4  bill_amt5  \
29245      50000   25      47053       5472       5891       6595       8400   
26498      50000   52      48195      49024      38085          0      10400   
20130      80000   43      68612      69971      71846      72372      73475   
25126     740000   50     321279     316083     317219     296560     285912   
20337      50000   61      52659      51213      51696      50422      30145   
...          ...  ...        ...        ...        ...        ...        ...   
28786     200000   36       8812      15189       6205      37658        696   
13687     320000   34        744       2291       2197       3934       5541   
11640      80000   27      55647      57737      58577      60169      58426   
13862     180000   26        390        390       5248       4167        780   
9699      130000   27     123371     125905     126524     127534     130524   

       bill_amt6  pay_amt1  pay_amt2  ...  pay_1  pay_2  pay_3  pay_4  pay_5  \
29245       4041      2000      1500  ...      0      0      0      2      0   
26498          0      2035      1650  ...      0      0      0      0     -1   
20130      74842      3100      3600  ...      2      0      0      0      0   
25126     268257     13000     13200  ...      0      0      0      0      0   
20337      30203         4      2346  ...      3      2      0      0      0   
...          ...       ...       ...  ...    ...    ...    ...    ...    ...   
28786       1430     15234      6225  ...     -1     -1     -1     -1      0   
13687       3141      2297      2203  ...     -1     -1     -1     -1     -1   
11640      58204      3000      3923  ...      0      0      0      0      0   
13862        467       390      5248  ...     -1     -1     -1      0     -1   
9699      132416      6000      4300  ...      1      2      2      2      2   

       pay_6  male  grad_school  university  married  
29245      0     1            1           0        1  
26498     -1     0            0           0        1  
20130      0     0            0           1        1  
25126      0     1            1           0        1  
20337      0     0            0           1        1  
...      ...   ...          ...         ...      ...  
28786     -1     0            0           1        1  
13687     -1     1            1           0        0  
11640      0     0            0           1        0  
13862     -1     0            0           1        0  
9699       2     1            0           1        0  

[24000 rows x 24 columns]

In [218]:
#Now, scaling needs too be done for x_train and x_test. For this, we are considering the numerical features (binary features not required)
sc_features = ["limit_bal", "age"] + bill_amt_features + pay_amt_features

In [219]:
from sklearn.preprocessing import StandardScaler

In [220]:
sc = StandardScaler()

In [221]:
x_train.loc[:,sc_features] = sc.fit_transform(x_train[sc_features])

In [222]:
x_test.loc[:,sc_features] = sc.fit_transform(x_test[sc_features])

The problem statement given is a Binary Classification where we need to find out. For this, we are using CLassification models under Supervised Learning

*   Logistic Regression Classifier
*   Decision Tree Classifier
*   Randm Forest Caasifier
*   Support Vector machine
*   KNN Classifier
*   Gradient Boost
*   Ada Boost
*   XG Boost


**Logistic Regression**

In [223]:
from sklearn.linear_model import LogisticRegression

In [224]:
lg=LogisticRegression()

In [225]:
lg.fit(x_train,y_train)

LogisticRegression()

In [226]:
type(lg)

sklearn.linear_model._logistic.LogisticRegression

In [227]:
x_test.shape

(6000, 24)

In [228]:
x_test.iloc[0] # first value in the column

limit_bal       1.619416
age            -0.596682
bill_amt1       4.489024
bill_amt2       4.347498
bill_amt3       4.388473
bill_amt4       3.898499
bill_amt5       2.495648
bill_amt6       4.487633
pay_amt1        0.454154
pay_amt2        0.565973
pay_amt3        0.208167
pay_amt4       -0.036131
pay_amt5       17.903913
pay_amt6        0.366442
pay_1           0.000000
pay_2           0.000000
pay_3           0.000000
pay_4           0.000000
pay_5           0.000000
pay_6          -1.000000
male            0.000000
grad_school     0.000000
university      1.000000
married         1.000000
Name: 22712, dtype: float64

In [229]:
y_pred=lg.predict(x_test)

In [230]:
y_pred

array([0, 0, 0, ..., 0, 0, 0])

In [231]:
y_pred.shape  #y_pred is the predicted values and y_test is the actual values

(6000,)

In [232]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC

In [233]:
from sklearn.metrics import accuracy_score,precision_score,recall_score, f1_score

In [234]:
acc=accuracy_score(y_test, y_pred)
pre=precision_score(y_test,y_pred)
recall=recall_score(y_test,y_pred)
f1=f1_score(y_test,y_pred)

In [235]:
print('Accuracy Score on Logistic Regression is : ',acc*100)
print('Precison Score on Logistic Regression is  : ',pre*100)
print('Recall Score on Logistic Regression is  : ',recall*100)
print('F1 Score on Logistic Regression is  : ',f1*100)

Accuracy Score on Logistic Regression is :  80.56666666666666
Precison Score on Logistic Regression is  :  68.0
Recall Score on Logistic Regression is  :  23.042168674698797
F1 Score on Logistic Regression is  :  34.4206974128234


In [236]:
from sklearn .metrics import roc_auc_score
auc =roc_auc_score(y_test,y_pred)

In [237]:
print('Area under the Curve(AUC) on Logistic Regression is : ',auc*100)

Area under the Curve(AUC) on Logistic Regression is :  59.979988446938435


In [238]:
#Generating Confusion Matrix
from sklearn.metrics import confusion_matrix

In [239]:
confusion_matrix(y_test,y_pred)

array([[4528,  144],
       [1022,  306]])

***Hyper Parameter tuning for Logisic Regression***

In [283]:
# define models and parameters
from sklearn.model_selection import RepeatedStratifiedKFold
from sklearn.model_selection import GridSearchCV
model = LogisticRegression()
solvers = ['newton-cg', 'lbfgs', 'liblinear']
penalty = ['l2']
c_values = [100, 10, 1.0, 0.1, 0.01]
# define grid search
grid = dict(solver=solvers,penalty=penalty,C=c_values)
cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)
grid_search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, cv=cv, scoring='accuracy',error_score=0)
grid_result = grid_search.fit(x_train, y_train)
# summarize results
print("Best: %f using %s" % (grid_result.best_score_, grid_result.best_params_))
means = grid_result.cv_results_['mean_test_score']
stds = grid_result.cv_results_['std_test_score']
params = grid_result.cv_results_['params']
for mean, stdev, param in zip(means, stds, params):
    print("%f (%f) with: %r" % (mean, stdev, param))

Best: 0.812097 using {'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
0.812069 (0.004635) with: {'C': 100, 'penalty': 'l2', 'solver': 'newton-cg'}
0.812097 (0.004655) with: {'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}
0.812069 (0.004635) with: {'C': 100, 'penalty': 'l2', 'solver': 'liblinear'}
0.812069 (0.004635) with: {'C': 10, 'penalty': 'l2', 'solver': 'newton-cg'}
0.812056 (0.004642) with: {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}
0.812083 (0.004642) with: {'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}
0.812056 (0.004666) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'newton-cg'}
0.812056 (0.004666) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'lbfgs'}
0.812097 (0.004691) with: {'C': 1.0, 'penalty': 'l2', 'solver': 'liblinear'}
0.811944 (0.004628) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'newton-cg'}
0.811958 (0.004622) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}
0.811986 (0.004694) with: {'C': 0.1, 'penalty': 'l2', 'solver': 'liblinear'}
0.811347 (0.004526) with: {

In [285]:
y_pred1=grid_result.predict(x_test)

In [289]:
acc1=accuracy_score(y_test, y_pred1)
pre1=precision_score(y_test,y_pred1)
recall1=recall_score(y_test,y_pred1)
f11=f1_score(y_test,y_pred)

In [290]:
print('Accuracy Score on Logistic Regression is : ',acc1*100)
print('Precison Score on Logistic Regression is  : ',pre1*100)
print('Recall Score on Logistic Regression is  : ',recall1*100)
print('F1 Score on Logistic Regression is  : ',f11*100)

Accuracy Score on Logistic Regression is :  80.56666666666666
Precison Score on Logistic Regression is  :  68.0
Recall Score on Logistic Regression is  :  23.042168674698797
F1 Score on Logistic Regression is  :  34.4206974128234


In [291]:
confusion_matrix(y_test,y_pred1)

array([[4528,  144],
       [1022,  306]])

**Decision Tree Classifier**

In [240]:
from sklearn.tree import DecisionTreeClassifier

In [241]:
dt=DecisionTreeClassifier()

In [242]:
dt.fit(x_train,y_train)

DecisionTreeClassifier()

In [243]:
y_preddt = dt.predict(x_test)

In [244]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accdt=accuracy_score(y_test, y_preddt)
predt=precision_score(y_test,y_preddt)
recalldt=recall_score(y_test,y_preddt)
f1dt=f1_score(y_test,y_preddt)
aucdt =roc_auc_score(y_test,y_preddt)

In [245]:
print('Accuracy Score on Decision Tree Classifier is : ',accdt*100)
print('Precison Score on Decision Tree Classifier is : ',predt*100)
print('Recall Score on Decision Tree Classifier is : ',recalldt*100)
print('F1 Score on Decision Tree Classifier is : ',f1dt*100)
print('Area under the Curve(AUC) on Decision Tree Classifier is : ',aucdt*100)

Accuracy Score on Decision Tree Classifier is :  70.38333333333333
Precison Score on Decision Tree Classifier is :  36.23543838136113
Recall Score on Decision Tree Classifier is :  44.50301204819277
F1 Score on Decision Tree Classifier is :  39.94592767826969
Area under the Curve(AUC) on Decision Tree Classifier is :  61.121369037795006


In [246]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_preddt)

array([[3632, 1040],
       [ 737,  591]])

**Random Forest Classifier**

In [247]:
from sklearn.ensemble import RandomForestClassifier

In [248]:
rf=RandomForestClassifier()

In [249]:
rf.fit(x_train,y_train)

RandomForestClassifier()

In [250]:
y_predrf=rf.predict(x_test)

In [251]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accrf=accuracy_score(y_test, y_predrf)
prerf=precision_score(y_test,y_predrf)
recallrf=recall_score(y_test,y_predrf)
f1rf=f1_score(y_test,y_predrf)
aucrf =roc_auc_score(y_test,y_predrf)

In [252]:
print('Accuracy Score on Random Forest Classifier is : ',accrf*100)
print('Precison Score on Random Forest Classifier is : ',prerf*100)
print('Recall Score on Random Forest Classifier is : ',recallrf*100)
print('F1 Score on Random Forest Classifier is : ',f1rf*100)
print('Area under the Curve(AUC) on Random Forest Classifier is : ',aucrf*100)

Accuracy Score on Random Forest Classifier is :  81.38333333333333
Precison Score on Random Forest Classifier is :  64.88011283497885
Recall Score on Random Forest Classifier is :  34.63855421686747
F1 Score on Random Forest Classifier is :  45.16445753559155
Area under the Curve(AUC) on Random Forest Classifier is :  64.6544654645981


In [253]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predrf)

array([[4423,  249],
       [ 868,  460]])

***Hyper parameter tuning for Random Forest Classifier***

In [293]:

param_grid = {
    'n_estimators': [25, 50, 100, 150],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [3, 6, 9],
    'max_leaf_nodes': [3, 6, 9],
}

In [294]:

grid_search = GridSearchCV(RandomForestClassifier(),
                           param_grid=param_grid)
grid_search.fit(x_train, y_train)
print(grid_search.best_estimator_)

RandomForestClassifier(max_depth=3, max_features=None, max_leaf_nodes=9)


In [303]:
model_grid = RandomForestClassifier(max_depth=9,
                                    max_features="log2",
                                    max_leaf_nodes=9,
                                    n_estimators=25)
model_grid.fit(x_train, y_train)
y_predrf1_grid = model_grid.predict(x_test)
print(classification_report(y_predrf1_grid, y_test))

              precision    recall  f1-score   support

           0       0.97      0.82      0.89      5492
           1       0.26      0.69      0.38       508

    accuracy                           0.81      6000
   macro avg       0.62      0.76      0.64      6000
weighted avg       0.91      0.81      0.85      6000



In [ ]:
#y_predrf1_grid=model_grid.predict(x_test)

In [304]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accrf1_grid=accuracy_score(y_test, y_predrf1_grid)
prerf1_grid=precision_score(y_test,y_predrf1_grid)
recallrf1_grid=recall_score(y_test,y_predrf1_grid)
f1rf1_grid=f1_score(y_test,y_predrf1_grid)
aucrf1_grid =roc_auc_score(y_test,y_predrf1_grid)

In [305]:
print('Accuracy Score on Random Forest Classifier is : ',accrf1_grid*100)
print('Precison Score on Random Forest Classifier is : ',prerf1_grid*100)
print('Recall Score on Random Forest Classifier is : ',recallrf1_grid*100)
print('F1 Score on Random Forest Classifier is : ',f1rf1_grid*100)
print('Area under the Curve(AUC) on Random Forest Classifier is : ',aucrf1_grid*100)

Accuracy Score on Random Forest Classifier is :  81.10000000000001
Precison Score on Random Forest Classifier is :  69.09448818897637
Recall Score on Random Forest Classifier is :  26.430722891566266
F1 Score on Random Forest Classifier is :  38.235294117647065
Area under the Curve(AUC) on Random Forest Classifier is :  61.53513884304341


**Support Vector Machine (SVM)**

In [254]:
from sklearn.svm import SVC
svm = SVC(kernel='linear')
svm.fit(x_train,y_train)

SVC(kernel='linear')

In [255]:
y_predsvm = svm.predict(x_test)

In [256]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accsvm=accuracy_score(y_test, y_predsvm)
presvm=precision_score(y_test,y_predsvm)
recallsvm=recall_score(y_test,y_predsvm)
f1svm=f1_score(y_test,y_predsvm)
aucsvm =roc_auc_score(y_test,y_predsvm)

In [257]:
print('Accuracy Score on SVM is : ',accsvm*100)
print('Precison Score on SVM is : ',presvm*100)
print('Recall Score on SVM is : ',recallsvm*100)
print('F1 Score on SVM is : ',f1svm*100)
print('Area under the Curve(AUC) on SVM is : ',aucsvm*100)

Accuracy Score on SVM is :  80.78333333333333
Precison Score on SVM is :  69.84126984126983
Recall Score on SVM is :  23.19277108433735
F1 Score on SVM is :  34.821933295647256
Area under the Curve(AUC) on SVM is :  60.173012254497436


In [258]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predsvm)

array([[4539,  133],
       [1020,  308]])

***Hyper Parameter tuning in SVM***

In [306]:
from sklearn.model_selection import GridSearchCV
  
# defining parameter range
param_grid = {'C': [0.1, 1, 10, 100, 1000], 
              'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
              'kernel': ['rbf']} 
  
svmgrid = GridSearchCV(SVC(), param_grid, refit = True, verbose = 3)
  
# fitting the model for grid search
svmgrid.fit(x_train, y_train)

Fitting 5 folds for each of 25 candidates, totalling 125 fits
[CV 1/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.783 total time=  46.9s
[CV 2/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.781 total time=  43.8s
[CV 3/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.782 total time=  59.3s
[CV 4/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.782 total time=  35.0s
[CV 5/5] END ........C=0.1, gamma=1, kernel=rbf;, score=0.782 total time=  42.7s
[CV 1/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.818 total time=  16.6s
[CV 2/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.817 total time=  13.9s
[CV 3/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.820 total time=  13.6s
[CV 4/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.813 total time=  13.3s
[CV 5/5] END ......C=0.1, gamma=0.1, kernel=rbf;, score=0.813 total time=  16.6s
[CV 1/5] END .....C=0.1, gamma=0.01, kernel=rbf;, score=0.812 total time=  11.0s
[CV 2/5] END .....C=0.1, gamma=0.01, kernel=rbf

GridSearchCV(estimator=SVC(),
             param_grid={'C': [0.1, 1, 10, 100, 1000],
                         'gamma': [1, 0.1, 0.01, 0.001, 0.0001],
                         'kernel': ['rbf']},
             verbose=3)

In [307]:

# print best parameter after tuning
print(svmgrid.best_params_)
  
# print how our model looks after hyper-parameter tuning
print(svmgrid.best_estimator_)

{'C': 1000, 'gamma': 0.001, 'kernel': 'rbf'}
SVC(C=1000, gamma=0.001)


In [308]:

y_predsvmgrid = svmgrid.predict(x_test)
  
# print classification report
print(classification_report(y_test, y_predsvmgrid))

              precision    recall  f1-score   support

           0       0.83      0.95      0.89      4672
           1       0.67      0.34      0.45      1328

    accuracy                           0.82      6000
   macro avg       0.75      0.64      0.67      6000
weighted avg       0.80      0.82      0.79      6000



In [309]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accsvmgrid=accuracy_score(y_test, y_predsvmgrid)
presvmgrid=precision_score(y_test,y_predsvmgrid)
recallsvmgrid=recall_score(y_test,y_predsvmgrid)
f1svmgrid=f1_score(y_test,y_predsvmgrid)
aucsvmgrid =roc_auc_score(y_test,y_predsvmgrid)

In [310]:
print('Accuracy Score on SVM is : ',accsvmgrid*100)
print('Precison Score on SVM is : ',presvmgrid*100)
print('Recall Score on SVM is : ',recallsvmgrid*100)
print('F1 Score on SVM is : ',f1svmgrid*100)
print('Area under the Curve(AUC) on SVM is : ',aucsvmgrid*100)

Accuracy Score on SVM is :  81.68333333333334
Precison Score on SVM is :  67.32223903177005
Recall Score on SVM is :  33.50903614457831
F1 Score on SVM is :  44.746103569632986
Area under the Curve(AUC) on SVM is :  64.44287423667272


**KNN Classifier**

In [259]:
from sklearn.neighbors import KNeighborsClassifier
classifier =KNeighborsClassifier(n_neighbors=5, metric='minkowski')
classifier.fit(x_train,y_train)
y_predknn =classifier.predict(x_test)

In [260]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accknn=accuracy_score(y_test, y_predknn)
preknn=precision_score(y_test,y_predknn)
recallknn=recall_score(y_test,y_predknn)
f1knn=f1_score(y_test,y_predknn)
aucknn =roc_auc_score(y_test,y_predknn)

In [261]:
print('Accuracy Score on KNN is : ',accknn*100)
print('Precison Score on KNN is : ',preknn*100)
print('Recall Score on KNN is : ',recallknn*100)
print('F1 Score on KNN is : ',f1knn*100)
print('Area under the Curve(AUC) on KNN is : ',aucknn*100)

Accuracy Score on KNN is :  79.23333333333333
Precison Score on KNN is :  54.88095238095239
Recall Score on KNN is :  34.713855421686745
F1 Score on KNN is :  42.52767527675277
Area under the Curve(AUC) on KNN is :  63.30084894372008


In [262]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predknn)

array([[4293,  379],
       [ 867,  461]])

**Gradient boosting classifier**

In [263]:
from sklearn.metrics import classification_report
from sklearn.ensemble import GradientBoostingClassifier

In [264]:
gradient_booster = GradientBoostingClassifier(learning_rate=0.1)
gradient_booster.fit(x_train,y_train)

GradientBoostingClassifier()

In [265]:
y_predgrad = gradient_booster.predict(x_test)

In [266]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accgrad=accuracy_score(y_test, y_predgrad)
pregrad=precision_score(y_test,y_predgrad)
recallgrad=recall_score(y_test,y_predgrad)
f1grad=f1_score(y_test,y_predgrad)
aucgrad =roc_auc_score(y_test,y_predgrad)

In [267]:
print('Accuracy Score on Gradient Boosting Classifier is : ',accgrad*100)
print('Precison Score on Gradient Boosting Classifier is : ',pregrad*100)
print('Recall Score on Gradient Boosting Classifier is : ',recallgrad*100)
print('F1 Score on Gradient Boosting Classifier is : ',f1grad*100)
print('Area under the Curve(AUC) on Gradient Boosting Classifier is : ',aucgrad*100)

Accuracy Score on Gradient Boosting Classifier is :  81.6
Precison Score on Gradient Boosting Classifier is :  65.55555555555556
Recall Score on Gradient Boosting Classifier is :  35.54216867469879
F1 Score on Gradient Boosting Classifier is :  46.09375000000001
Area under the Curve(AUC) on Gradient Boosting Classifier is :  65.1169747483083


In [268]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predgrad)

array([[4424,  248],
       [ 856,  472]])

**ADA Boost Classifier**

In [269]:
from sklearn.ensemble import AdaBoostClassifier

In [270]:
ADA = AdaBoostClassifier(DecisionTreeClassifier(max_depth=1),n_estimators=200)
ADA.fit(x_train, y_train)

AdaBoostClassifier(estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=200)

In [271]:
y_predada = ADA.predict(x_test)

In [272]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accada=accuracy_score(y_test, y_predada)
preada=precision_score(y_test,y_predada)
recallada=recall_score(y_test,y_predada)
f1ada=f1_score(y_test,y_predada)
aucada =roc_auc_score(y_test,y_predada)

In [273]:
print('Accuracy Score on ADA Boost Classifier is : ',accada*100)
print('Precison Score on ADA Boost Classifier is : ',preada*100)
print('Recall Score on ADA Boost Classifier is : ',recallada*100)
print('F1 Score on ADA Boost Classifier is : ',f1ada*100)
print('Area under the Curve(AUC) on ADA Boost Classifier is : ',aucada*100)

Accuracy Score on ADA Boost Classifier is :  81.45
Precison Score on ADA Boost Classifier is :  66.31259484066769
Recall Score on ADA Boost Classifier is :  32.9066265060241
F1 Score on ADA Boost Classifier is :  43.985908404630095
Area under the Curve(AUC) on ADA Boost Classifier is :  64.07745708862849


In [274]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predada)

array([[4450,  222],
       [ 891,  437]])

**XG Boost Classifier**

In [275]:
from xgboost import XGBClassifier

In [276]:
xgb = XGBClassifier()
xgb.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [277]:
y_predxgb = xgb.predict(x_test)

In [278]:
#evaluate ML model using accuracy,precision. recall, f1 score, AUC
accxgb=accuracy_score(y_test, y_predxgb)
prexgb=precision_score(y_test,y_predxgb)
recallxgb=recall_score(y_test,y_predxgb)
f1xgb=f1_score(y_test,y_predxgb)
aucxgb =roc_auc_score(y_test,y_predxgb)

In [279]:
print('Accuracy Score on XG Boost Classifier is : ',accxgb*100)
print('Precison Score on XG Boost Classifier is : ',prexgb*100)
print('Recall Score on XG Boost Classifier is : ',recallxgb*100)
print('F1 Score on XG Boost Classifier is : ',f1xgb*100)
print('Area under the Curve(AUC) on XG Boost Classifier is : ',aucxgb*100)

Accuracy Score on XG Boost Classifier is :  80.63333333333334
Precison Score on XG Boost Classifier is :  61.277173913043484
Recall Score on XG Boost Classifier is :  33.96084337349398
F1 Score on XG Boost Classifier is :  43.701550387596896
Area under the Curve(AUC) on XG Boost Classifier is :  63.93033607030863


In [280]:
#Generating Confusion Matrix
confusion_matrix(y_test,y_predxgb)

array([[4387,  285],
       [ 877,  451]])

## From the above, it is clearly seen that different models provide different accuracies.